#!/usr/bin/env bash
SETTINGS="${HYPR_POLISH_SETTINGS:-$HOME/.config/hypr/settings.json}"
OUT="$HOME/.config/hypr/polish.conf"

anim=$(jq -r '.hyprPolishAnimations // "subtle"' "$SETTINGS" 2>/dev/null)
dim=$(jq -r '.hyprPolishDimInactive // "off"' "$SETTINGS" 2>/dev/null)

case "$anim" in
    off)
        beziers=()
        anims=()
        enabled=no
        ;;
    juicy)
        enabled=yes
        beziers=("pop,0.18,1.0,0.3,1.22" "smooth,0.22,0.85,0.25,1" "snap,0.3,0,0.2,1")
        anims=(
            "windows,1,2.8,pop,popin 80%"
            "windowsOut,1,2,snap,popin 82%"
            "fadeIn,1,2.4,smooth"
            "fadeOut,1,1.8,snap"
            "fade,1,2.4,smooth"
            "layers,1,2.4,smooth,fade"
            "layersIn,1,2.4,smooth,fade"
            "layersOut,1,1.8,snap,fade"
            "workspaces,1,3,pop,slide"
            "specialWorkspaceIn,1,2.8,pop,slidevert"
            "specialWorkspaceOut,1,2.2,snap,slidevert"
            "border,1,2.4,smooth"
            "borderangle,0"
        )
        ;;
    *)
        enabled=yes
        beziers=("pop,0.2,0.9,0.3,1.05" "smooth,0.25,0.8,0.25,1" "snap,0.3,0,0.2,1")
        anims=(
            "windows,1,2.2,pop,popin 90%"
            "windowsOut,1,1.6,snap,popin 92%"
            "fadeIn,1,2,smooth"
            "fadeOut,1,1.5,snap"
            "fade,1,2,smooth"
            "layers,1,2,smooth,fade"
            "layersIn,1,2,smooth,fade"
            "layersOut,1,1.5,snap,fade"
            "workspaces,1,2.4,smooth,slide"
            "specialWorkspaceIn,1,2.4,smooth,slidevert"
            "specialWorkspaceOut,1,1.8,snap,slidevert"
            "border,1,2,smooth"
            "borderangle,0"
        )
        ;;
esac

case "$dim" in
    subtle) dim_on=true; dim_str=0.07 ;;
    strong) dim_on=true; dim_str=0.16 ;;
    *) dim_on=false; dim_str=0.0 ;;
esac

{
    echo "# Generated by hypr_polish_apply.sh — edit via Guide > HYPRLAND POLISH"
    echo "animations {"
    echo "    enabled = $enabled"
    for b in "${beziers[@]}"; do echo "    bezier = ${b}"; done
    for a in "${anims[@]}"; do echo "    animation = ${a}"; done
    echo "}"
    echo "decoration {"
    echo "    dim_inactive = $dim_on"
    echo "    dim_strength = $dim_str"
    echo "}"
} > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"

command -v hyprctl >/dev/null || exit 0
hyprctl keyword animations:enabled "$([ "$enabled" = yes ] && echo 1 || echo 0)" >/dev/null 2>&1
for b in "${beziers[@]}"; do hyprctl keyword bezier "$b" >/dev/null 2>&1; done
for a in "${anims[@]}"; do hyprctl keyword animation "$a" >/dev/null 2>&1; done
hyprctl keyword decoration:dim_inactive "$([ "$dim_on" = true ] && echo 1 || echo 0)" >/dev/null 2>&1
hyprctl keyword decoration:dim_strength "$dim_str" >/dev/null 2>&1
exit 0
